version: "3"
services:
  frontend:
    # build: .
    image: go-micro-service:latest
    entrypoint: go-micro-services frontend
    links:
      - otel-collector
      - search
      - profile
    depends_on:
      - search
      - profile

  frontend-proxy:
    # build: ./services/proxy
    image: fit-proxy:latest
    environment:
      - PROXY_HOST=0.0.0.0:8080
      - PROXY_TARGET=http://frontend:8080
      - SERVICE_NAME=frontend
      - COLLECTOR_HOST=collector:5000
    env_file:
      - .env
    ports:
      - "5000:8080"

  search:
    # build: ./services/proxy
    image: fit-proxy:latest
    environment:
      - PROXY_HOST=0.0.0.0:8080
      - PROXY_TARGET=http://search-service:8080
      - COLLECTOR_HOST=collector:5000
      - SERVICE_NAME=search
      - USE_HTTP2=true
    env_file:
      - .env
  search-service:
    # build: .
    image: go-micro-service:latest
    entrypoint: go-micro-services search
    links:
      - geo
      - rate
      - otel-collector
  profile:
    # build: ./services/proxy
    image: fit-proxy:latest
    environment:
      - PROXY_HOST=0.0.0.0:8080
      - PROXY_TARGET=http://profile-service:8080
      - COLLECTOR_HOST=collector:5000
      - SERVICE_NAME=profile
      - USE_HTTP2=true
    env_file:
      - .env
  profile-service:
    # build: .
    image: go-micro-service:latest
    entrypoint: go-micro-services profile
    links:
      - geo
      - rate
      - otel-collector

  geo:
    # build: ./services/proxy
    image: fit-proxy:latest
    environment:
      - PROXY_HOST=0.0.0.0:8080
      - PROXY_TARGET=http://geo-service:8080
      - COLLECTOR_HOST=collector:5000
      - SERVICE_NAME=geo
      - USE_HTTP2=true
    env_file:
      - .env
    ports:
      - "5011:8080"

  geo-service:
    # build: .
    image: go-micro-service:latest
    entrypoint: go-micro-services geo
    links:
      - otel-collector

  rate:
    # build: ./services/proxy
    image: fit-proxy:latest
    environment:
      - PROXY_HOST=0.0.0.0:8080
      - PROXY_TARGET=http://rate-service:8080
      - COLLECTOR_HOST=collector:5000
      - SERVICE_NAME=rate
      - USE_HTTP2=true
    env_file:
      - .env
  rate-service:
    # build: .
    image: go-micro-service:latest
    entrypoint: go-micro-services rate
    links:
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./otel-collector-config.yaml:/otel-collector-config.yaml
    command: --config=/otel-collector-config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
    links:
      - jaeger
      - collector

  collector:
    # build: ./services/collector
    image: fit-otel-collector:latest
    volumes:
      - ./services/collector:/collector
    command: flask --app /collector/collector.py --debug run --host=0.0.0.0
    ports:
      - "5010:5000"

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
