version: "3"
services:
  frontend:
    build: .
    entrypoint: go-micro-services frontend
    ports:
      - "5000:8080"
    links:
      - jaeger
      - search
      - profile
    depends_on:
      - search
      - profile

  search-service:
    build: .
    entrypoint: go-micro-services search
    links:
      - geo
      - rate
      - jaeger

  search:
    image: envoyproxy/envoy-alpine:v1.21-latest
    depends_on:
      - search-service
    volumes:
      - ./internal/services/search/envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "9901:9901"

  profile:
    build: .
    entrypoint: go-micro-services profile
    links:
      - geo
      - rate
      - jaeger

      - 
  geo:
    build: .
    entrypoint: go-micro-services geo
    links:
      - jaeger

  rate:
    build: .
    entrypoint: go-micro-services rate
    links:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:1.2.0
    ports:
      - "14269"
      - "5778:5778"
      - "14268:14268"
      - "14267"
      - "16686:16686"
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
