version: "3"
services:
  frontend:
    build: .
    entrypoint: go-micro-services frontend
    links:
      - otel-collector
      - search
      - profile
    depends_on:
      - search
      - profile
    ports:
      - "5000:8080"
    environment:
      - NO_INSTRUMENTATION=true

  search:
    build: .
    entrypoint: go-micro-services search
    links:
      - geo
      - rate
      - otel-collector
    environment:
      - NO_INSTRUMENTATION=true
  profile:
    build: .
    entrypoint: go-micro-services profile
    links:
      - geo
      - rate
      - otel-collector
    environment:
      - NO_INSTRUMENTATION=true
  geo:
    build: .
    entrypoint: go-micro-services geo
    links:
      - otel-collector
    environment:
      - NO_INSTRUMENTATION=true
  rate:
    build: .
    entrypoint: go-micro-services rate
    links:
      - otel-collector
    environment:
      - NO_INSTRUMENTATION=true

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./otel-collector-config.base.yaml:/otel-collector-config.yaml
    command: --config=/otel-collector-config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
    links:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
